# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512)),
                ('artista', models.CharField(max_length=512)),
                ('portada', models.FileField(upload_to=b'')),
            ],
            options={
                'db_table': 'discos',
                'verbose_name_plural': 'discos',
            },
        ),
    ]
